### ISSUE TITLE
[css]ios兼容问题

### ISSUE THREAD

**Issue by QoVoQ** [jaweii/vueg#15]
https://github.com/jaweii/vueg/blob/029f63565f272786a1b541438cc3709900d1015a/css/transition.css#L11-L26

弱弱地问下，上面这几行代码有什么作用？

我在开发中发现，上面这几行css会导致无限滚动列表中的ul/a/button元素出现渲染延迟的情况，在安卓手机上尤其明显

![ezgif-5-9a2178072f](https://user-images.githubusercontent.com/17191224/32484475-f04173a0-c3da-11e7-864b-51558b7512ab.gif)

![image](https://user-images.githubusercontent.com/17191224/32484568-45bb3ea6-c3db-11e7-8882-e3cc8fddace3.png)

**Comment by jaweii** [comment]
这是因为使用引入的animate.css集成后，在ios上部分动画会出现异常，然后经过调试，发现加上那个代码就正常了。
