### ISSUE TITLE
引入main.js后直接报错

### ISSUE THREAD

**Issue by yangxuilyx** [jaweii/vueg#16]
根据文档安装完成，import之后报下面的错

`in ./~/vueg/index.js
Module parse failed: ...\Assets\node_modules\vueg\index.js Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <<<<<<< Updated upstream
| "use strict";var transition={};transition.install=function(t,n){function e(){var t=this.$el.classList;if(t){var n=[];Object.keys(t).forEach(function(e){n.push(t[e])});var e=!1;if(n.map(function(t){"animated"===t&&(e=!0)}),e){var a=document.createElement("div");a.id="vueg-background";var i=m.default;if(i){var o=i.$data.vuegConfig;if(o&&Object.keys(o).forEach(function(t){f[t]=o[t]}),f.disable)return;var r=document.getElementById("vueg-background");r||(i.$el.parentElement.appendChild(a),r=a),r.innerHTML="",r.classList=[],r.appendChild(this.$el)}}}}function a(){return!(!this.vuegConfig||!1!==this.vuegConfig.disable)||(!m||!m.default||m.default._uid===this._uid)}function i(){var t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:this;if(a.call(t)&&t&&!1!==l.value&&d){var n=this.$el;if(n&&n.parentElement){r(),Object.keys(s).forEach(function(t){f[t]=s[t]});var e=this.$data.vuegConfig;e&&Object.keys(e).forEach(function(t){f[t]=e[t]}),f.disable&&(u=""),f.shadow&&(n.style.boxShadow="0 3px 10px rgba(0, 0, 0, .156863), 0 3px 10px rgba(0, 0, 0, .227451)"),"first"===u&&(n.style.animationDuration=f.firstEntryDuration+"s",n.classList.add("fadeIn")),u&&(n.style.animationDuration=f.duration+"s"),n.classList.add("animated");var i=["touchPoint"],o=void 0;switch(u){case"forward":o=f.forwardAnim;break;case"back":o=f.backAnim}o&&n.classList.add(o);var c=void 0,m=document.head||document.getElementsByTagName("head")[0],v=void 0;if((c=document.getElementById("vueg-style"))||((c=document.createElement("style")).type="text/css",c.id="vueg-style",m.appendChild(c)),-1!==i.findIndex(function(t){return t===o}))switch(o){case"touchPoint":var p={x:document.documentElement.clientWidth/2,y:document.documentElement.clientHeight/2};v=".touchPoint{\n                                max-height:"+document.documentElement.clientHeight+"px!important;\n                                overflow:hidden;\n                                animation-name:touchPoint;\n                                position: relative;\n                                animation-timing-function: linear;\n                            }\n                            @keyframes touchPoint {\n                                from {\n                                    opacity:0.5;\n                                    transform: scale3d(0, 0, 0);\n                                    left:"+(-p.x+h.x)+"px;\n                                    top:"+(-p.y+h.y)+"px;\n                                }\n                                to{ \n                                    opacity:1;\n                                    transform: scale3d(1, 1, 1);\n                                    left:0;\n                                    top:0;\n                                }\n                            }";var g=document.createTextNode(v);c.appendChild(g)}setTimeout(function(){n.classList.remove(f.forwardAnim),n.classList.remove(f.backAnim),n.style.animationDuration="0s";var t=document.getElementById("vueg-background");t&&(t.innerHTML=""),-1!==i.findIndex(function(t){return t===o})&&(c.innerHTML="")},1e3*f.duration+300),setTimeout(function(){n.classList.remove("fadeIn")},1e3*f.firstEntryDuration)}}}function o(t){"mousedown"===t.type?(h.x=t.pageX,h.y=t.pageY):(h.x=t.touches[0].pageX,h.y=t.touches[0].pageY)}function r(){f={duration:"0.3",firstEntryDisable:!1,firstEntryDuration:".6",forwardAnim:"fadeInRight",backAnim:"fadeInLeft",sameDepthDisable:!1,tabs:[],tabsDisable:!1,disable:!1,shadow:!0}}var s=arguments.length>2&&void 0!==arguments[2]?arguments[2]:{},d=void 0,c=void 0,u=void 0,l={},f=void 0,m=void 0,h={x:0,y:0};r(),t.directive("transition",{bind:function(t,n,e,a){l=n}}),t.mixin({mounted:i,activated:i,beforeDestroy:e,deactivated:e}),n.beforeEach(function(t,n,e){d=t;var a=t.path.split("/").length,i=n.path.split("/").length;if("/"!==t.path.charAt(t.path.length-1)&&(a+=1),"/"!==n.path.charAt(n.path.length-1)&&(i+=1),u=a>i?"forward":"back",a===i&&(u=c===t.path?"back":"forward",f.sameDepthDisable&&(u=""),c=n.path),t.path===n.path&&t.path===c&&(u="first"),f.firstEntryDisable&&(u=""),n.name&&t.name){var o=f.tabs.findIndex(function(t){return t.name===n.name}),r=f.tabs.findIndex(function(n){return n.name===t.name});f.tabsDisable||-1===o||-1===r?-1!==o&&-1!==r&&(u=""):(r>o&&(u="forward"),r<o&&(u="back"),r===o&&(u=""))}var s=t.matched[0];m=s&&s.instances?s.instances:null,e()}),document.addEventListener("mousedown",o),document.addEventListener("touchstart",o)},module.exports=transition;
| =======
 @ ./src/main.js 19:0-24
 @ multi ./build/dev-client ./src/main.js`

**Comment by jaweii** [comment]
合并后造成的报错，已经解决重新发布了。

**Comment by yangxuilyx** [comment]
好的，谢谢
