### ISSUE TITLE
新版本编译报错

### ISSUE THREAD

**Issue by sixinyiyu** [jaweii/vueg#17]
"vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vueg": "^1.2.6",
    "vuex": "^3.0.0",
    "vuex-router-sync": "^5.0.0"

![image](https://user-images.githubusercontent.com/3435446/32733220-a3e95c72-c8c9-11e7-8f2b-e34b7321e791.png)

![image](https://user-images.githubusercontent.com/3435446/32733206-9cab947a-c8c9-11e7-96bd-fa11f7b551bb.png)

**Comment by IOJINDD** [comment]
vueg下的 index.js 出错，应该是合并的时候有冲突，没及时解决，你把index.js文件上面压缩的代码 删了，试试

**Comment by jaweii** [comment]
确实是合并后，造成的报错，已经解决重新发布了。
