### ISSUE TITLE
嵌套路由转场时左侧出现空白，不是转场的目标页面覆盖原页面效果

### ISSUE THREAD

**Issue by wujiabk** [jaweii/vueg#18]
默认配置
const options={  
    duration: '0.3',              //转场动画时长，默认为0.3，单位秒
    forwardAnim: 'fadeInRight',   //前进动画，默认为fadeInRight  
    backAnim: 'fadeInRight'     //后退动画，默认为fedeInLeft  
}

**Comment by jaweii** [comment]
描述不是很清晰，能否提供重现部分的项目代码？

**Comment by wujiabk** [comment]
就是转场的时候从右至做进场动画，左侧底部不是上一个页面的内容而是一片空白的，可能是跳转路由后上一个路由内容被直接干掉了，出现新的路由内容造成底部是白色底的空白

**Comment by jaweii** [comment]
@wujiabk sorry， 嵌套路由的“底色”还没有做支持
