### ISSUE TITLE
Error in beforeDestroy hook: "TypeError: Cannot set property classList of #<Element> which has only a getter"

### ISSUE THREAD

**Issue by sprout-echo** [jaweii/vueg#19]
我就按照demo写的，报了这个错误 Error in beforeDestroy hook: "TypeError: Cannot set property classList of #<Element> which has only a getter"

准确的是两个错误：
TypeError: Cannot set property classList of #<Element> which has only a getter(…)

emmm,不是很懂

**Comment by jaweii** [comment]
相同的问题https://github.com/jaweii/vueg/issues/8
查阅下你的vueg引入顺序，和文档中要求的一样吗
