### ISSUE TITLE
DEMO 安卓4.4 vuex需要引入polyfill

### ISSUE THREAD

**Issue by HopeFE** [jaweii/vueg#2]
![image](https://user-images.githubusercontent.com/22955719/27215905-01614418-52a6-11e7-904e-1bbf29e1b100.png)

**Comment by jaweii** [comment]
按住4.4版本算比较低的了，所以可能是兼容性问题，不知道具体情况也无法确定
可以参考这个试试：http://www.cnblogs.com/weiqinl/p/6794612.html

**Comment by weixisheng** [comment]
![image](https://user-images.githubusercontent.com/16042305/27269683-6fa15502-54eb-11e7-9ba0-75cf282cbfd9.png)

**Comment by jaweii** [comment]
@weixisheng 看下你的main.js和package.json

**Comment by weixisheng** [comment]
## main.js
...
import VueRouter from 'vue-router';
import vueg from 'vueg';
import 'vueg/css/transition-min.css'
Vue.use(vueg, VueRouter);
## package.json
dependencies:{
  "vue": "^2.3.3",
    "vue-router": "^2.2.0",
    "vueg": "^1.2.45",
    "vuex": "^2.1.1",
    ...
}

**Comment by jaweii** [comment]
Vue.use(vueg, router)     //←注意这一句应该在router实例化(router = new VueRouter({})之后

有可能是这个原因

**Comment by weixisheng** [comment]
![image](https://user-images.githubusercontent.com/16042305/27269936-5bbcd672-54ed-11e7-93f4-02da598becdd.png)

尴尬、把vueg位置放错了。解决了
