### ISSUE TITLE
请问在路由的命名视图中正常工作吗？

### ISSUE THREAD

**Issue by YYQ8023** [jaweii/vueg#21]
本来应该自己实验一下的，不过还是提issues了，见谅！

计划今晚会去试，试完也会反馈！

主要一个问题是，在命名视图中，路由是改变的，但是视图并不是全部改变的。
这里是vue-router的官方例子[命名视图](https://jsfiddle.net/posva/6du90epg/)
那么不变的部分会有动画吗？

期望的是，变化的才有动画。
谢谢！

例子中，中间一部分 “bar” 这个`router-view`没有变化，而是同级的`router-view`变化了，此时这个“bar”是如何展示的？

对了，这个主要是为webapp设计的，那么在pc端呢？效果怎么样！（我今晚回去试！）

**Comment by jaweii** [comment]
动画的触发是写在路由的全局后置钩子(afterEach)里，也就是说只要route变化了，就会触发，不同的route使用同一个组件，还是会触发。我没有测试，估计三个都会有变化。
