### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bigmeow** [jaweii/vueg#22]
1. IOS下DEMO页面，当跳转页面后，使用IOS自带的右滑返回，动画会重复执行，效果感人

2.页面A的高度超过一屏，在页面A先滑动到底部，然后跳转页面B；然后点击返回，切换效果空白闪烁很严重

ps:第一个问题我之前的想法是监听首饰，当右滑一定距离时，给全局一个状态标志；然后用户的右滑动作触发了系统的返回，在路由里检测到了这个状态标志，就不触发载入动画

**Comment by polkYu** [comment]
微信以及某些浏览器有返回的功能，返回的动画会重复，有时返回后再点击一个页面，动画和我预定义的不一样，有啥办法解决吗~

**Comment by jaweii** [comment]
本次重构包含解决此Issue
