### ISSUE TITLE
用了这个之后，单个页面高度超出一屏之后就没办法滑动了

### ISSUE THREAD

**Issue by wuyingfeng1992** [jaweii/vueg#23]
用了这个之后，单个页面高度超出一屏之后就没办法滑动了

**Comment by wuyingfeng1992** [comment]
要把    touch-action: none;改成就可以了
    touch-action: pan-y;

**Comment by jaweii** [comment]
参考demo，超出使可以滑动的

**Comment by wddclass** [comment]
@jaweii 
demo里写了overflow:hidden，虽然里边的列表写了auto，但ios设备仍会滑动卡顿，
就算加上-webkit-overflow-scrolling: touch;属性，也仍有偶尔卡顿的bug，不知能否去掉overflow:hidden属性或者改为可选
