### ISSUE TITLE
为什么我设置了没有效果呢

### ISSUE THREAD

**Issue by zxzhgk** [jaweii/vueg#25]
![image](https://user-images.githubusercontent.com/13518792/37263063-5cf01728-25e1-11e8-803d-0c7b87ed850c.png)

**Comment by zxzhgk** [comment]
然后报错 Failed to resolve directive: transition

**Comment by zxzhgk** [comment]
大神求看一下，我看了我和demo的代码是一样的不知道为啥报错

**Comment by jaweii** [comment]
抱歉，刚看到。
我猜测可能是你的引入方式造成的，你按照文档里的方式引入：
`Vue.use(vueg, router)`
