### ISSUE TITLE
iOS 下返回时会闪烁

### ISSUE THREAD

**Issue by WalterZou** [jaweii/vueg#3]
RT，由于不是使用的 vue-router 的 transition，clone 了 dom 作为背景，这样不能保持原来的滚动位置，会出现 out 的页面会滚动到最上面（其实不是同一个 dom），在 iOS 下有比较明显的闪烁。
PS: 初步判断是这个原因，但是只出现在返回时的动画...

**Comment by jaweii** [comment]
可以录个gif看看吗，顺便附上package.json
demo中没有这个情况的 你可以参考参考
