### ISSUE TITLE
使用keep-alive组件缓存后，页面动画进出的顺序乱了

### ISSUE THREAD

**Issue by 594904020** [jaweii/vueg#30]
使用keep-alive组件缓存后，页面动画进出的顺序乱了，怎么解决呢

**Comment by jaweii** [comment]
没有遇到过。能否描述详细？

**Comment by 594904020** [comment]
`  <keep-alive>
     <router-view v-transition/>
   </keep-alive>`

有A，B，C页面，A页面中点击按钮跳转B，点击B中按钮跳转C，
其中vueg配置中前进动画为“fadeInRight”  ，后退动画为“fadeInLeft”；

当我使用vue的keep-alive对组件进行缓存后。

A跳B页面，B跳C页面过程中，B跳C的前进动画变成了fadeInLeft。

**Comment by zz-33** [comment]
在keep-alive的情况，尤其是多个页面keep-alive，完全不能用了这个插件：
A首页(keep-alive)-->B列表页(keep-alive)-->C详情页，A->B->C->B正常；
A->B->C->B-(反了)->A，A->B->C->B-(反了)->C
