### ISSUE TITLE
转场出现拖影的

### ISSUE THREAD

**Issue by skyzfdance** [jaweii/vueg#31]
<router-view v-transition></router-view> 之后，确定设定其组件为height:100vh，路由变换时，会出现上一级界面内容延迟1S 后才会消失，无论是前进 还是后退 都有这个问题出现，能请您帮助一下吗

**Comment by jaweii** [comment]
是这样子的，上一级界面会作为“底色”，确保新界面动画完成后才会被移除，你只需要让新界面在旧界面的顶层(z-index)就可以了。
