### ISSUE TITLE
页面切换的时候会重叠到一起

### ISSUE THREAD

**Issue by yoking-shi** [jaweii/vueg#32]
手机端页面。页面切换的时候会两个页面重叠到一起，这个怎么解决

**Comment by jackyting825** [comment]
@yoking-shi 重叠的问题你解决了吗?用背景色貌似可以解决文字重叠,但是图片重叠不行

**Comment by jaweii** [comment]
背景 + z-index就可以解决了。

**Comment by yoking-shi** [comment]
@jaweii 谢谢，已经搞定了，现在才看到，因为后来翻到issues里边之前有人提过这个问题。
@jackyting825 背景+ z-index
