### ISSUE TITLE
页面切换的时候会残留上一页的元素，过了一秒后才消失，有没有类似mode="out-in"之类的设置

### ISSUE THREAD

**Issue by wujianrong** [jaweii/vueg#33]
页面切换的时候会残留上一页的元素，过了一秒后才消失，有没有类似mode="out-in"之类的设置
vue-router里面有mode="out-in"的设置，可以设置当旧的页面完全消失了，新的页面才进入
https://cn.vuejs.org/v2/guide/transitions.html#%E8%BF%87%E6%B8%A1%E6%A8%A1%E5%BC%8F
请问大神，这插件有没有这样的功能

**Comment by jaweii** [comment]
你可以给正在进入的页面设置更高优先级的z-index，就可以挡住旧页面了。
