### ISSUE TITLE
ios上手势滑动返回上一页动画

### ISSUE THREAD

**Issue by kevinlvhsl** [jaweii/vueg#37]
如题，在ios上的网页，手势右侧滑动可以返回上一页， demo中提供的过渡，在上一页面已经滑到右边的情况下，过渡还是会播放一次。 有办法解决这个问题吗？

**Comment by David2k13** [comment]
我也遇到了这个问题.vux的dome解决了这个问题,正在研究他的源码

**Comment by jaweii** [comment]
本次重构包含解决此Issue
