### ISSUE TITLE
你好 转场的时候会出现闪耀

### ISSUE THREAD

**Issue by Jiiiiiin** [jaweii/vueg#4]
如题，我使用的是vux组件库，很多页面外部嵌套了better-scroll，有没有一个配置是设置【逐隐】的？还是能根本解决闪耀就更好了！

**Comment by Jiiiiiin** [comment]
我设置了：
 duration: '.3',              // 转场动画时长，默认为0.3，单位秒 / `animation-duration`
  firstEntryDisable: true,     // 值为true时禁用首次进入应用时的渐现动画，默认为false / When the value is true, in the process of the user into the app, app no transition effect,the default is false
  firstEntryDuration: '.3',
这个配置 稍微好了一点，但是 还是出现，页面已经切换之后，还是会【留有上一个】页面的【片段内容】！

**Comment by evolutionjay** [comment]
非常的库啊,  就是转场效果比较生硬. 调整下 
``` css
transition-timing-function: cubic-bezier(0, 1, 0.5, 1);
```

不提 new  issue 了,直接丢 closed 的 issue.
