### ISSUE TITLE
多层路由嵌套的时候，转场作用不到子router-view

### ISSUE THREAD

**Issue by Jiiiiiin** [jaweii/vueg#5]
如题，是否能解决呢？
`
export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home,
      meta: {
        title: '首页'
      }
    },
    {
      path: '/Phone',
      component: EmptyTmpl,
      children: [
        {
          path: 'Public',
          component: EmptyTmpl,`

每个EmptyTmpl模板中有一个router-view。

**Comment by jaweii** [comment]
文档里有写到，嵌套路由默认是关闭转场动画的，需要在组件中配置为开启：
```
`    data(){
        return {
            vuegConfig:{  
                disable:false              //对于嵌套路由，默认为关闭动画，需要在组件的data.vuegConfig中配置disable为false启用
            }
    }
}`
```
