### ISSUE TITLE
路由全是单层的，无法使用

### ISSUE THREAD

**Issue by ifredom** [jaweii/vueg#9]
路由结构是这样： 
const router = [{
  path: '/',
  component: App,
  children: [{
      path: '/',
      redirect: '/login' //默认路由，直接重定向到地址 /login
    },
    {
      path: '/login',
      component: Login
    },
    {
      path: '/home',
      component: Home
    },
    {
      path: '/register', //注册
      component: Register
    }]
}]

跳转就是this.$router.push('XXXX')

**Comment by jaweii** [comment]
都是同级路由的的话，只能通过历史记录做简单的判断前进后退的，但是你可以通过js动态修改插件配置的方式，来控制每个页面的进场、出场所使用的动画
